server:
  port: ${SERVER_PORT:8082}

debug: false

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ms-academico-grupo-7-arquitetura-de-software
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: info
    org.springframework: info
    org.hibernate.SQL: warn